version: 0.2
phases:
  install:
    runtime-versions:
      php: 8.0
    commands:
      - echo Logging in to Amazon ECR....
      - aws --version
      - echo Build started on `date`
      # login to Elastic container registry
      - eval $(aws ecr get-login --region us-west-2 --no-include-email | sed 's|https://||')
      - REPOSITORY_URI=244799856984.dkr.ecr.us-west-2.amazonaws.com/temp-www
      - IMAGE_TAG=1.0
      - php --version
      - php -m
      - php -r "readfile('http://getcomposer.org/installer');" | php -- --install-dir=/usr/bin/ --filename=composer

      - apt-get -y install mlocate
  build:
    commands:
      - echo Installing composer deps
      - composer install --no-progress --no-suggest
      - echo CREATING .env FILE..
      - cp .env.example .env
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Printing ecr log
      - cat ./.ecr/log/*
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker image ls -a
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - docker push $REPOSITORY_URI:$IMAGE_TAG
