version: 0.2
phases:
  install:
    commands:
      - curl -s https://getcomposer.org/installer | php
      - mv  composer.phar /usr/local/bin/composer
      - php --version
      - composer
      - apt-get update
      - apt-get install mlocate
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer update
      - cp .env.example .env
      - php artisan cache:clear
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - '**/*'
  name: learnMix-$(date +%Y-%m-%d)